### ISSUE TITLE
Unknown integer variables break bitvector coercion

### ISSUE THREAD

**Issue by katrinafyi** [UQ-PAC/asl-interpreter#11]
The presence of an integer variable with an unknown will break the current integer-to-bitvector logic. This is because the logic is not able to infer bounds on the size of these variables. 

For example:
```bash
integer HighestSetBit6__6 ;

if eq_bits.0 {{ 1 }} ( Exp4__5 [ 1 +: 1 ],'1' ) then {
  HighestSetBit6__6 = 1 ;
  }  else {
    if eq_bits.0 {{ 1 }} ( Exp4__5 [ 0 +: 1 ],'1' ) then {
      HighestSetBit6__6 = 0 ;
    }  else {
      HighestSetBit6__6 = -1 ;
    }
  }
}

// later use of HighestSetBit6__6...
__array _R [ 0 ] = ZeroExtend.0 {{ 32,64 }} ( sub_int.0 {{  }} ( 32,add_int.0 {{  }} ( Exp7__6,1 ) ) [ 0 +: 32 ],64 ) ;
```
This causes the following error:
>   Error Failure("bits_size_of_expr: no type known for Exp7__6")

A more detailed analysis would would have to be flow-sensitive and take into account an approximation of all code paths, considering all assignments to a particular variable.

In the short term, it's maybe possible to match the case where only constants are assigned. 

Happens at [aarch64_integer_arithmetic_cnt](https://github.com/UQ-PAC/asl-interpreter/blob/bbc27fe9edb13d44de7b66f2e09b1e4622d349b3/tests/coverage/aarch64_integer___#L1756), e.g. 0x5ac01000.

**Comment by ncough** [comment]
Gave the basic approach a shot over the weekend, but vector instructions (e.g. `0x4e205800`) use integer accumulators that mess everything up. Ended up implementing the full analysis in #13, which seems to address of the failures in the coverage tests.

**Comment by ncough** [comment]
#13 has been merged, this should no longer be an issue.
