### ISSUE TITLE
Non-primitive function cannot be disassembled

### ISSUE THREAD

**Issue by JamesP797** [UQ-PAC/asl-interpreter#3]
Multiple cases where we hit the final error case in `dis_funcall` of `dis.ml`, resulting in an `EvalError`. This occurs from a `catcherror`, so it might be worth temporarily removing this to find out what the problem actually is.  
Cases where this error occurs:
- aarch64_integer_crc: `0x1ac04000`
- aarch64_branch_conditional_compare: `0x34000000`
- aarch64_branch_conditional_cond: `0x54000000`
- aarch64_branch_conditional_test: `0x36000000`
- aarch64_branch_unconditional_immediate: `0x14000000`
- aarch64_branch_unconditional_register: `0xd61f0000`
- aarch64_memory_atomicops_cas_single: `0x8a07c00`
- aarch64_memory_atomicops_ld... (most of the memory instruction fail here)

**Comment by katrinafyi** [comment]
All of the opcodes listed except the last disassemble successfully for me. They do need the tests/overrides.asl file to be included.

What error is being thrown? The last case of dis_funcall should re-raise the exception with the same details.

**Comment by JamesP797** [comment]
Is there anything different you have locally? I have the latest of the plugin and asli, but if I run:
```
bap-mc --show-bir --arch=aarch64 --primus-lisp-semantics=disable \
--a64-main-prelude=$HOME/asl-interpreter/prelude.asl \
--a64-main-specs=$HOME/mra_tools/arch/regs.asl \
--a64-main-specs=$HOME/mra_tools/types.asl \
--a64-main-specs=$HOME/mra_tools/arch/arch.asl \
--a64-main-specs=$HOME/mra_tools/arch/arch_instrs.asl \
--a64-main-specs=$HOME/mra_tools/arch/arch_decode.asl \
--a64-main-specs=$HOME/asl-interpreter/tests/override.asl \
-- 00 40 c0 1a
```
I get the error. I've noticed you've said `overrides.asl` and not `override.asl`, is there perhaps a missing file?  

Also it turns out when I run everything from BAP the exception isn't re-raised properly, I can run it from ASLi and see more information. Thanks for the heads up

**Comment by katrinafyi** [comment]
override.asl would be right, I misremembered the name. 

Strange that the exception isn't there from bap, but these should work correctly with the latest partial_eval branch.

The integer and branch ones in particular are expected to pass as in the CI tests: https://github.com/UQ-PAC/asl-interpreter/tree/partial_eval/tests/coverage

**Comment by katrinafyi** [comment]
@JamesP797 Thanks for including the command, I was able to see the error. 

It looks like this is caused because the command doesn't include `support/feature.asl` which sets some feature flags which the original asl-interpreter supports. Adding this lets aarch64_integer_crc succeed, but the branch instructions still fail somewhere else inside the lifter.

Eventually, we might want to more strictly define the ARM features we want/need, but this file should be ok for now.

I've also tweaked some things in asl-interpreter and the a64-plugin to show better exception traces on the bap side (https://github.com/UQ-PAC/asl-interpreter/commit/3ae7871704b009d6260f91b828abd780c5d07fd0, https://github.com/UQ-PAC/bap/commit/70a403d786d3d59f93dbd0753f673643c73966d1). For example, the CRC error without feature.asl looks like this:
```pascal
  LibASL.Value.EvalError("unnamed IMPLEMENTATION_DEFINED behavior") at file "/home/rina/mra_tools/arch/arch.asl" line 229 char 11 - line 230 char 0

... at file "/home/rina/mra_tools/arch/arch.asl" line 229 char 11 - line 230 char 0: dis_stmt --> return or_bool.0 {{  }} ( eq_enum.8 {{  }} ( version,ARMv8p0 ),boolean IMPLEMENTATION_DEFINED  ) ;
... at file "/home/rina/mra_tools/arch/arch.asl" line 15504 char 11 - line 15505 char 0: dis_call --> HasArchVersion.0 {{  }} ( 1 )
... at file "/home/rina/mra_tools/arch/arch.asl" line 15504 char 11 - line 15505 char 0: dis_expr --> HasArchVersion.0 {{  }} ( ARMv8p1 )
... at file "/home/rina/mra_tools/arch/arch.asl" line 15504 char 11 - line 15505 char 0: dis_expr --> or_bool.0 {{  }} ( HasArchVersion.0 {{  }} ( ARMv8p1 ),boolean IMPLEMENTATION_DEFINED Have CRC extension )
... [and so on]
```

**Comment by JamesP797** [comment]
Thanks for looking into that, sorry it turns out the bash script I wrote for a single opcode didn't have all of the args that the coverage one did. Fixed in [`4733e41`](https://github.com/UQ-PAC/asl-interpreter/commit/4733e41b5e4689ae3e0946384ddb153364fc1e50). I'll verify all of these opcodes no longer throw the exception early next week, most of the new errors I've seen are just missing variables in the lifter which should be a simple fix.

**Comment by JamesP797** [comment]
I've made updates to the a64 lifter on the BAP side so now only the final opcode errors

**Comment by katrinafyi** [comment]
The last opcode, 0x08a07c00 casb w0, w0, [x0], now disassembles after #19. There's still some excess complexity from the BigEndian() call, but this could be overriden later if we need to.

**Comment by katrinafyi** [comment]
Done in #19.
