### ISSUE TITLE
adopt aslt grammar into this repository 

### ISSUE THREAD

**Issue by katrinafyi** [UQ-PAC/asl-interpreter#45]
by aslt, I mean the AST-like format for semantics used by basil and emitted by gtirb-semantics.

this format might eventually be used more widely and it will be useful to move the antlr grammar here for visibility and maintenance.

**Comment by mmcloughlin** [comment]
What does the `t` in `aslt` stand for?

**Comment by katrinafyi** [comment]
@mmcloughlin, the t stands for text. This is just to avoid confusion with the .asl files which have a very different format.
