### ISSUE TITLE
BAP doesn't recognise an instruction

### ISSUE THREAD

**Issue by JamesP797** [UQ-PAC/asl-interpreter#5]
Passing in some valid opcodes results in BAP giving a `X bytes bytes were left non disassembled` error. This occurs even when using the primus lifter, with the a64 lifter disabled, so it is likely that this issue is out of scope for this project.  
Cases where the issue occurs:  
- aarch64_integer_arithmetic_mcsubtracttaggedaddress[setflags]: `0xbac10021`, `0x9ac10021`
- aarch64_integer_flags_rmif: `0xba000400`, `0x3a00080d`
- aarch64_memory_ordered_rcpc
- aarch64_memory_single_general_immediate_signed_offset_lda_stl

**Comment by JamesP797** [comment]
It's possible that this only occurs when running them individually, and when in a sequence of related instructions it is fine.

**Comment by ncough** [comment]
I suspect that, for some of these cases, LLVM hasn't been configured to support the instructions. For example, to support the aarch64_integer_flags_rmif cases, you need to set the `+flagm` attribute. To test these, you can use `llvm-mc`:
```
echo '0x00 0x04 0x00 0xba' | llvm-mc -disassemble -arch=aarch64 --mattr=+flagm
```
You can find these options in the following: https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Support/AArch64TargetParser.def

I'm not sure how this lines up to the BAP side of things. I think you can specify certain target properties somehow.

**Comment by ncough** [comment]
Not a problem on our end of things.
